version: '3.8'

services:
  sourdough-docs:
    image: 10.9.8.121:5000/sourdough-docs:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          # Option 1: If you've labeled the node with 'docker node update --label-add name=worker-2 <NODE_ID>'
          # - node.labels.name == worker-2
          
          # Option 2: If the hostname matches the IP
          # - node.hostname == 10.9.8.122
          
          # Option 3: Deploy to any worker (will pick one randomly)
          - node.role == worker
          
          # Option 4: If you know the specific node ID (get from 'docker node ls')
          # - node.id == <NODE_ID>
          
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    ports:
      - "8080:80"
    networks:
      - sourdough-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sourdough-net:
    driver: overlay
    attachable: true