version: '3.8'

services:
  sourdough-docs:
    image: 10.9.8.121:5000/sourdough-docs:latest
    secrets:
      - registry-auth
    deploy:
      replicas: 1
      placement:
        constraints:
          # Deploy to worker-2 where we confirmed registry access works
          - node.hostname == swarm-worker-2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    ports:
      - "8081:80"
    networks:
      - sourdough-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sourdough-net:
    driver: overlay
    attachable: true

secrets:
  registry-auth:
    external: true