site_name: MaK's Sourdough Journey
site_url: https://example.com
site_description: MaK's personal journey mastering sourdough baking, with technical guidance from CodeCrust
site_author: MaK & CodeCrust

dev_addr: 0.0.0.0:5555

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/bread-slice
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md
  - Getting Started:
    - Your First Loaf: getting-started/first-loaf.md
    - Starter Readiness: getting-started/starter-readiness.md
  - Recipes:
    - Basic Sourdough: recipes/basic-sourdough.md
  - Techniques:
    - Folding & Shaping: techniques/folding-shaping.md
  - Tools:
    - Ingredient Calculator: tools/calculator.md
  - Blog:
    - Blog Home: blog/index.md
    - Setting Up CI/CD: blog/posts/cicd-journey.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/git-kubik/sourdough-journey
  generator: false

extra_css:
  - stylesheets/extra.css
  
copyright: Copyright &copy; 2025 MaK & CodeCrust - Mastering the art of sourdough and code