#!/bin/bash

# Setup script to label swarm nodes and prepare for deployment

SWARM_MANAGER="10.9.8.120"

echo "🔧 Setting up Docker Swarm nodes for deployment..."
echo ""
echo "This script will help you label your swarm nodes for proper deployment."
echo "Run this on the Swarm manager (${SWARM_MANAGER})"
echo ""
echo "Your Swarm setup:"
echo "  Manager: 10.9.8.120"
echo "  Workers: 10.9.8.121, 10.9.8.122, 10.9.8.123"
echo ""
echo "To label nodes on the Swarm manager, run these commands:"
echo ""
echo "# First, list all nodes to get their IDs:"
echo "docker node ls"
echo ""
echo "# Then label the nodes (replace NODE_ID with actual IDs):"
echo "docker node update --label-add name=worker-1 <NODE_ID_FOR_10.9.8.121>"
echo "docker node update --label-add name=worker-2 <NODE_ID_FOR_10.9.8.122>"
echo "docker node update --label-add name=worker-3 <NODE_ID_FOR_10.9.8.123>"
echo ""
echo "# To deploy specifically to worker-2 (10.9.8.122), update docker-compose.swarm.yml:"
echo "# Change the constraint to:"
echo "#   - node.labels.name == worker-2"
echo ""
echo "# Or to deploy to a specific IP (if hostnames match IPs):"
echo "#   - node.hostname == 10.9.8.122"